name: "Mail on push"
on: [push, pull_request]

jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      # email sender
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Push in ${{github.repository}}!
          body: ${{github.event.pusher.name}} puhed a commit in ${{github.repository}}. Message - ${{github.event.head_commit.message}}
          to: chris.kottisse@voco.ee
          from: Github actions
