name: "Mail on push"
on: [push, pull_request]
env:
   AUTHOR: ${{ github.event.pusher.name }}
   REPOSITORY: ${{ github.repository }}
   MESSAGE: ${{ github.event.head_commit.message }}


jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      # email sender
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Push in $REPOSITORY!
          body: $AUTHOR puhed a commit in $REPOSITORY. "Message:" $MESSAGE
          to: chris.kottisse@voco.ee
          from: Github actions