name: "File checker"
on: [push, pull_request]
env:
   AUTHOR: ${{ github.event.pusher.name }}

jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      # email sender
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ github.event.pusher.name }} pushed to ${{github.repository}}!
          body: Workflow ${{ github.workflow }} in ${{ github.repository }} was pushed by ${{ github.event.pusher.name }}. "Message:" ${{ github.event.head_commit.message }}
          to: chris.kottisse@voco.ee
          from: Github actions