name: Analyze code statically
"on": pull_request
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using misspell
        uses: moneyforward/misspell-action@v0
  # chat-pull-request
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: Google chatroom message
        uses: ipacheco-uy/actions-chat@v2.0.2
        with:
          # Google Chat Webhook URL
          url: ${{ secrets.https://chat.googleapis.com/v1/spaces/AAAAxxSJKSM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=z4f0hx2hD5kQEIFRh4Qzq3KfJXwIbD2YBvdzaHztuxg%3D }}
          project: AA
          jiraHost: https://jira.com